version: '3.1'

services:
  app:
    build: ./CoreBaseC/.
    ports:
      - "3003:3003"
    volumes:
      - ./CoreBaseC/
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'basec'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '51ngba13'
      MYSQL_ROOT_PASSWORD: '51ngba13'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:


